services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/azure-sql-edge
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
  rabbitmq:
    image: rabbitmq:3.10.6-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/ECommerce.Services.Catalog/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/ECommerce.IdentityServer/Dockerfile
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/ECommerce.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/PhotoStock/ECommerce.Services.PhotoStock/Dockerfile
  discount.api:
    image: discount_api_image
    build:
      context: .
      dockerfile: Services/Discount/ECommerce.Services.Discount/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
