services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=AdminPass123.
      - POSTGRES_DB=Discount
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=SaPass123.
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1444"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=SaPass123.
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl:rabbitmq
      - IdentityServerURL:http://identityserver.api:5001
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb