services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/azure-sql-edge
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
  rabbitmq:
    image: rabbitmq:3.10.6-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/ECommerce.Services.Catalog/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
